// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/sum.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int32                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int32                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_sum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_sum_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Request) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_sum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_sum_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_proto_sum_proto protoreflect.FileDescriptor

const file_proto_sum_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/sum.proto\x12\x03sum\"%\n" +
	"\aRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x05R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x05R\x01b\"\"\n" +
	"\bResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result2\xcb\x01\n" +
	"\x11CalculatorService\x12,\n" +
	"\tAddStream\x12\f.sum.Request\x1a\r.sum.Response(\x010\x01\x12,\n" +
	"\tSubStream\x12\f.sum.Request\x1a\r.sum.Response(\x010\x01\x12,\n" +
	"\tMulStream\x12\f.sum.Request\x1a\r.sum.Response(\x010\x01\x12,\n" +
	"\tDivStream\x12\f.sum.Request\x1a\r.sum.Response(\x010\x01B\x12Z\x10bai1/proto;protob\x06proto3"

var (
	file_proto_sum_proto_rawDescOnce sync.Once
	file_proto_sum_proto_rawDescData []byte
)

func file_proto_sum_proto_rawDescGZIP() []byte {
	file_proto_sum_proto_rawDescOnce.Do(func() {
		file_proto_sum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sum_proto_rawDesc), len(file_proto_sum_proto_rawDesc)))
	})
	return file_proto_sum_proto_rawDescData
}

var file_proto_sum_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sum_proto_goTypes = []any{
	(*Request)(nil),  // 0: sum.Request
	(*Response)(nil), // 1: sum.Response
}
var file_proto_sum_proto_depIdxs = []int32{
	0, // 0: sum.CalculatorService.AddStream:input_type -> sum.Request
	0, // 1: sum.CalculatorService.SubStream:input_type -> sum.Request
	0, // 2: sum.CalculatorService.MulStream:input_type -> sum.Request
	0, // 3: sum.CalculatorService.DivStream:input_type -> sum.Request
	1, // 4: sum.CalculatorService.AddStream:output_type -> sum.Response
	1, // 5: sum.CalculatorService.SubStream:output_type -> sum.Response
	1, // 6: sum.CalculatorService.MulStream:output_type -> sum.Response
	1, // 7: sum.CalculatorService.DivStream:output_type -> sum.Response
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sum_proto_init() }
func file_proto_sum_proto_init() {
	if File_proto_sum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sum_proto_rawDesc), len(file_proto_sum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sum_proto_goTypes,
		DependencyIndexes: file_proto_sum_proto_depIdxs,
		MessageInfos:      file_proto_sum_proto_msgTypes,
	}.Build()
	File_proto_sum_proto = out.File
	file_proto_sum_proto_goTypes = nil
	file_proto_sum_proto_depIdxs = nil
}
